apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: hello-world-image
spec:
  type: image
  params:
    - name: url
      value: quay.io/lordofthejars/hello-world-quarkus-tekton:1.0.0