apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: kubectl-deploy-run
spec:
  params:
    - name: deploymentFile
      value: src/main/kubernetes/kubernetes.yml
  resources:
    inputs:
      - name: source
        resourceRef:
          name: git-source
      - name: builtImage
        resourceRef:
          name: hello-world-image
  taskRef:
    name: kubectl-deploy